INSERT ALL
  --tabela astronauta --
  INTO ASTRONAUTA (NOME, NASCIMENTO) VALUES ('Neil Armstrong', TO_TIMESTAMP('1930-08-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO ASTRONAUTA (NOME, NASCIMENTO) VALUES ('Yuri Gagarin', TO_TIMESTAMP('1934-03-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO ASTRONAUTA (NOME, NASCIMENTO) VALUES ('Valentina Tereshkova', TO_TIMESTAMP('1937-03-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO ASTRONAUTA (NOME, NASCIMENTO) VALUES ('Buzz Aldrin', TO_TIMESTAMP('1930-01-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO ASTRONAUTA (NOME, NASCIMENTO) VALUES ('Sally Ride', TO_TIMESTAMP('1951-05-26 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))

  --tabela estrela --
  INTO ESTRELA (NOME, TAMANHO, BINARIO) VALUES ('Sol', 'Médio', 0)
  INTO ESTRELA (NOME, TAMANHO, BINARIO) VALUES ('Alpha Centauri A', 'Grande', 0)
  INTO ESTRELA (NOME, TAMANHO, BINARIO) VALUES ('Kepler-186', 'Médio', 0)
  INTO ESTRELA (NOME, TAMANHO, BINARIO) VALUES ('TRAPPIST-1', 'Pequeno', 1)
  INTO ESTRELA (NOME, TAMANHO, BINARIO) VALUES ('Gliese 581', 'Pequeno', 0)
  INTO ESTRELA (NOME, TAMANHO, BINARIO) VALUES ('HD 219134', 'Grande', 0)


  --tabela planeta --
  INTO PLANETA (NOME, TAMANHO, NIVEL_DE_SEGURANCA, DISTANCIA_DA_ESTRELA, CALOR, TRANSLACAO, ROTACAO, ESTRELA) VALUES ('Terra', 'Médio', 'Alto', 1.000000, 25.5, 365, 24, 'Sol')
  INTO PLANETA (NOME, TAMANHO, NIVEL_DE_SEGURANCA, DISTANCIA_DA_ESTRELA, CALOR, TRANSLACAO, ROTACAO, ESTRELA) VALUES ('Marte', 'Pequeno', 'Médio', 1.547842, -55, 687, 25, 'Sol')
  INTO PLANETA (NOME, TAMANHO, NIVEL_DE_SEGURANCA, DISTANCIA_DA_ESTRELA, CALOR, TRANSLACAO, ROTACAO, ESTRELA) VALUES ('Júpiter', 'Grande', 'Baixo',  5.200000, -145, 4333, 10, 'Sol')
  INTO PLANETA (NOME, TAMANHO, NIVEL_DE_SEGURANCA, DISTANCIA_DA_ESTRELA, CALOR, TRANSLACAO, ROTACAO, ESTRELA) VALUES ('Saturno', 'Grande', 'Médio', 9.369755, -178, 10759, 11, 'Sol')
  INTO PLANETA (NOME, TAMANHO, NIVEL_DE_SEGURANCA, DISTANCIA_DA_ESTRELA, CALOR, TRANSLACAO, ROTACAO, ESTRELA) VALUES ('Epsilon Prime', 'Pequeno', 'Médio', 0.23, 300, 55, 1200, 'Alpha Centauri A')
  INTO PLANETA (NOME, TAMANHO, NIVEL_DE_SEGURANCA, DISTANCIA_DA_ESTRELA, CALOR, TRANSLACAO, ROTACAO, ESTRELA) VALUES ('Próxima b', 'Pequeno', 'Alto', 0.04, 234, 11, 45, 'Alpha Centauri A')
  INTO PLANETA (NOME, TAMANHO, NIVEL_DE_SEGURANCA, DISTANCIA_DA_ESTRELA, CALOR, TRANSLACAO, ROTACAO, ESTRELA) VALUES ('Kepler-186f', 'Médio', 'Baixo', 0.35, 220, 130, 180, 'Kepler-186')
  INTO PLANETA (NOME, TAMANHO, NIVEL_DE_SEGURANCA, DISTANCIA_DA_ESTRELA, CALOR, TRANSLACAO, ROTACAO, ESTRELA) VALUES ('TRAPPIST-1d', 'Médio', 'Médio', 0.02, 170, 4, 6, 'TRAPPIST-1')
  INTO PLANETA (NOME, TAMANHO, NIVEL_DE_SEGURANCA, DISTANCIA_DA_ESTRELA, CALOR, TRANSLACAO, ROTACAO, ESTRELA) VALUES ('Gliese 581g', 'Grande', 'Baixo', 0.15, 260, 37, 66, 'Gliese 581')
  INTO PLANETA (NOME, TAMANHO, NIVEL_DE_SEGURANCA, DISTANCIA_DA_ESTRELA, CALOR, TRANSLACAO, ROTACAO, ESTRELA) VALUES ('HD 219134b', 'Pequeno', 'Alto', 0.04, 300, 6, 32, 'HD 219134')


  --tabela planeta--
  INTO DESCOBRE_PLANETA ("DATA", ASTRONAUTA, PLANETA) VALUES (TO_TIMESTAMP('2022-01-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Neil Armstrong', 'Terra')
  INTO DESCOBRE_PLANETA ("DATA", ASTRONAUTA, PLANETA) VALUES (TO_TIMESTAMP('2022-02-15 09:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Yuri Gagarin', 'Marte')
  INTO DESCOBRE_PLANETA ("DATA", ASTRONAUTA, PLANETA) VALUES (TO_TIMESTAMP('2022-05-05 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Sally Ride', 'Saturno')
  INTO DESCOBRE_PLANETA ("DATA", ASTRONAUTA, PLANETA) VALUES (TO_TIMESTAMP('2022-11-01 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Neil Armstrong', 'Epsilon Prime')
  INTO DESCOBRE_PLANETA ("DATA", ASTRONAUTA, PLANETA) VALUES (TO_TIMESTAMP('2022-10-10 07:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Sally Ride', 'Próxima b')
  INTO DESCOBRE_PLANETA ("DATA", ASTRONAUTA, PLANETA) VALUES (TO_TIMESTAMP('2022-11-02 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Yuri Gagarin', 'Kepler-186f')
  INTO DESCOBRE_PLANETA ("DATA", ASTRONAUTA, PLANETA) VALUES (TO_TIMESTAMP('2022-11-03 15:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'Valentina Tereshkova', 'TRAPPIST-1d')
  INTO DESCOBRE_PLANETA ("DATA", ASTRONAUTA, PLANETA) VALUES (TO_TIMESTAMP('2022-11-04 18:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Buzz Aldrin', 'Gliese 581g')
  INTO DESCOBRE_PLANETA ("DATA", ASTRONAUTA, PLANETA) VALUES (TO_TIMESTAMP('2022-11-05 22:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Sally Ride', 'HD 219134b')

  --tabela luas--
  INTO LUAS (NOME, PLANETA) VALUES ('Lua', 'Terra')
  INTO LUAS (NOME, PLANETA) VALUES ('Fobos', 'Marte')
  INTO LUAS (NOME, PLANETA) VALUES ('Deimos', 'Marte')
  INTO LUAS (NOME, PLANETA) VALUES ('Titan', 'Saturno')
  INTO LUAS (NOME, PLANETA) VALUES ('Enceladus', 'Saturno')
  INTO LUAS (NOME, PLANETA) VALUES ('Lunaris', 'Epsilon Prime')
  INTO LUAS (NOME, PLANETA) VALUES ('Estelar', 'Próxima b')
  INTO LUAS (NOME, PLANETA) VALUES ('Orbitante', 'Kepler-186f')
  INTO LUAS (NOME, PLANETA) VALUES ('Trappistiano', 'TRAPPIST-1d')
  INTO LUAS (NOME, PLANETA) VALUES ('Gliesiano', 'Gliese 581g')
  INTO LUAS (NOME, PLANETA) VALUES ('HD Moon', 'HD 219134b')

  --tabela bioma--
  INTO BIOMA (TIPO, NIVEL_DE_RADIACAO, NIVEL_DE_TOXIDADE) VALUES ('Floresta Temperada', 'Médio', 'Baixo')
  INTO BIOMA (TIPO, NIVEL_DE_RADIACAO, NIVEL_DE_TOXIDADE) VALUES ('Floresta Tropical', 'Alto', 'Médio')
  INTO BIOMA (TIPO, NIVEL_DE_RADIACAO, NIVEL_DE_TOXIDADE) VALUES ('Deserto', 'Alto', 'Alto')
  INTO BIOMA (TIPO, NIVEL_DE_RADIACAO, NIVEL_DE_TOXIDADE) VALUES ('Tundra', 'Baixo', 'Baixo')
  INTO BIOMA (TIPO, NIVEL_DE_RADIACAO, NIVEL_DE_TOXIDADE) VALUES ('Pastos', 'Médio', 'Baixo')

  --tabela ambiente--
  INTO AMBIENTE (PLANETA, BIOMA) VALUES ('Terra', 'Floresta Temperada')
  INTO AMBIENTE (PLANETA, BIOMA) VALUES ('Marte', 'Deserto')
  INTO AMBIENTE (PLANETA, BIOMA) VALUES ('Saturno', 'Pastos')
  INTO AMBIENTE (PLANETA, BIOMA) VALUES ('Júpiter', 'Deserto')
  INTO AMBIENTE (PLANETA, BIOMA) VALUES ('Epsilon Prime', 'Tundra')
  INTO AMBIENTE (PLANETA, BIOMA) VALUES ('Próxima b', 'Deserto')
  INTO AMBIENTE (PLANETA, BIOMA) VALUES ('Kepler-186f', 'Floresta Temperada')
  INTO AMBIENTE (PLANETA, BIOMA) VALUES ('TRAPPIST-1d', 'Floresta Tropical')
  INTO AMBIENTE (PLANETA, BIOMA) VALUES ('Gliese 581g', 'Pastos')
  INTO AMBIENTE (PLANETA, BIOMA) VALUES ('HD 219134b', 'Tundra')


  --tabela elemento quimico--
  INTO ELEMENTO_QUIMICO (SIGLA) VALUES ('H')
  INTO ELEMENTO_QUIMICO (SIGLA) VALUES ('Ru')
  INTO ELEMENTO_QUIMICO (SIGLA) VALUES ('Fe')
  INTO ELEMENTO_QUIMICO (SIGLA) VALUES ('Li')
  INTO ELEMENTO_QUIMICO (SIGLA) VALUES ('Al')
  INTO ELEMENTO_QUIMICO (SIGLA) VALUES ('Be')
  INTO ELEMENTO_QUIMICO (SIGLA) VALUES ('B')
  INTO ELEMENTO_QUIMICO (SIGLA) VALUES ('Zn')
  INTO ELEMENTO_QUIMICO (SIGLA) VALUES ('Cu')
  INTO ELEMENTO_QUIMICO (SIGLA) VALUES ('Si')
  INTO ELEMENTO_QUIMICO (SIGLA) VALUES ('C')
  INTO ELEMENTO_QUIMICO (SIGLA) VALUES ('N')
  INTO ELEMENTO_QUIMICO (SIGLA) VALUES ('Ni')
  INTO ELEMENTO_QUIMICO (SIGLA) VALUES ('O')
  INTO ELEMENTO_QUIMICO (SIGLA) VALUES ('F')
  INTO ELEMENTO_QUIMICO (SIGLA) VALUES ('Au')
  INTO ELEMENTO_QUIMICO (SIGLA) VALUES ('Ne')

  --tabela minerio--
  INTO MINERIO (NOME, TIPO, DUREZA, ELEMENTO, QUANTIDADE) VALUES ('Minério de Ferro', 'Metálico', '5', 'Fe', 120.5)
  INTO MINERIO (NOME, TIPO, DUREZA, ELEMENTO, QUANTIDADE) VALUES ('Minério de Ouro', 'Precioso', '7', 'Au', 25.2)
  INTO MINERIO (NOME, TIPO, DUREZA, ELEMENTO, QUANTIDADE) VALUES ('Sílica', 'Não Metálico', '4', 'Si', 80.8)
  INTO MINERIO (NOME, TIPO, DUREZA, ELEMENTO, QUANTIDADE) VALUES ('Minério de Cobre', 'Metálico', '6', 'Cu', 45.3)
  INTO MINERIO (NOME, TIPO, DUREZA, ELEMENTO, QUANTIDADE) VALUES ('Diamante', 'Precioso', '10', 'C', 2.1)
  INTO MINERIO (NOME, TIPO, DUREZA, ELEMENTO, QUANTIDADE) VALUES ('Bauxita', 'Metálico', '8', 'Al', 60.0)
  INTO MINERIO (NOME, TIPO, DUREZA, ELEMENTO, QUANTIDADE) VALUES ('Minério de Zinco', 'Metálico', '6', 'Zn', 35.7)
  INTO MINERIO (NOME, TIPO, DUREZA, ELEMENTO, QUANTIDADE) VALUES ('Carvão Mineral', 'Não Metálico', '3', 'C', 150.2)
  INTO MINERIO (NOME, TIPO, DUREZA, ELEMENTO, QUANTIDADE) VALUES ('Minério de Níquel', 'Metálico', '7', 'Ni', 42.6)
  INTO MINERIO (NOME, TIPO, DUREZA, ELEMENTO, QUANTIDADE) VALUES ('Rutênio', 'Metálico', '9', 'Ru', 15.3)

  --tabela possui--
  INTO POSSUI (AMBIENTE, MINERIO) VALUES ('Terra', 'Minério de Ferro')
  INTO POSSUI (AMBIENTE, MINERIO) VALUES ('Marte', 'Minério de Ouro')
  INTO POSSUI (AMBIENTE, MINERIO) VALUES ('Júpiter', 'Sílica')
  INTO POSSUI (AMBIENTE, MINERIO) VALUES ('Marte', 'Minério de Cobre')
  INTO POSSUI (AMBIENTE, MINERIO) VALUES ('Terra', 'Diamante')
  INTO POSSUI (AMBIENTE, MINERIO) VALUES ('Terra', 'Bauxita')
  INTO POSSUI (AMBIENTE, MINERIO) VALUES ('Marte', 'Minério de Zinco')
  INTO POSSUI (AMBIENTE, MINERIO) VALUES ('Júpiter', 'Carvão Mineral')
  INTO POSSUI (AMBIENTE, MINERIO) VALUES ('Marte', 'Minério de Níquel')
  INTO POSSUI (AMBIENTE, MINERIO) VALUES ('Marte', 'Rutênio')


  --tabela tipo de fauna_flora --
  INTO TIPO_DE_FAUNA_FLORA (AMBIENTE, TIPO) VALUES ('Terra', 'Mamífero')
  INTO TIPO_DE_FAUNA_FLORA (AMBIENTE, TIPO) VALUES ('Marte', 'Réptil')
  INTO TIPO_DE_FAUNA_FLORA (AMBIENTE, TIPO) VALUES ('Terra', 'Ave')
  INTO TIPO_DE_FAUNA_FLORA (AMBIENTE, TIPO) VALUES ('Marte', 'Inseto')
  INTO TIPO_DE_FAUNA_FLORA (AMBIENTE, TIPO) VALUES ('Júpiter', 'Anfíbio')
  INTO TIPO_DE_FAUNA_FLORA (AMBIENTE, TIPO) VALUES ('Próxima b', 'Ave')
  INTO TIPO_DE_FAUNA_FLORA (AMBIENTE, TIPO) VALUES ('Kepler-186f', 'Mamífero')
  INTO TIPO_DE_FAUNA_FLORA (AMBIENTE, TIPO) VALUES ('TRAPPIST-1d', 'Réptil')
  INTO TIPO_DE_FAUNA_FLORA (AMBIENTE, TIPO) VALUES ('Gliese 581g', 'Anfíbio')
  INTO TIPO_DE_FAUNA_FLORA (AMBIENTE, TIPO) VALUES ('HD 219134b', 'Mamífero')

  --tabela tipo de minerio--
  INTO TIPO_DE_MINERIO (AMBIENTE, TIPO) VALUES ('Terra', 'Metálico')
  INTO TIPO_DE_MINERIO (AMBIENTE, TIPO) VALUES ('Marte', 'Precioso')
  INTO TIPO_DE_MINERIO (AMBIENTE, TIPO) VALUES ('Terra', 'Não Metálico')
  INTO TIPO_DE_MINERIO (AMBIENTE, TIPO) VALUES ('Marte', 'Metálico')
  INTO TIPO_DE_MINERIO (AMBIENTE, TIPO) VALUES ('Terra', 'Precioso')
  INTO TIPO_DE_MINERIO (AMBIENTE, TIPO) VALUES ('Marte', 'Não Metálico')
  INTO TIPO_DE_MINERIO (AMBIENTE, TIPO) VALUES ('Júpiter', 'Metálico')

  --tabela perigo--
  INTO PERIGO (AMBIENTE, NOME) VALUES ('Terra', 'Tempestade')
  INTO PERIGO (AMBIENTE, NOME) VALUES ('Marte', 'Tempestade de Areia')
  INTO PERIGO (AMBIENTE, NOME) VALUES ('Terra', 'Terremoto')
  INTO PERIGO (AMBIENTE, NOME) VALUES ('Marte', 'Redemoinho de Poeira')
  INTO PERIGO (AMBIENTE, NOME) VALUES ('Júpiter', 'Tempestade Elétrica')
  INTO PERIGO (AMBIENTE, NOME) VALUES ('Próxima b', 'Tempestade de Raios')
  INTO PERIGO (AMBIENTE, NOME) VALUES ('Kepler-186f', 'Tempestade de Gelo')
  INTO PERIGO (AMBIENTE, NOME) VALUES ('TRAPPIST-1d', 'Tempestade de Poeira')
  INTO PERIGO (AMBIENTE, NOME) VALUES ('Gliese 581g', 'Tempestade de Raios')
  INTO PERIGO (AMBIENTE, NOME) VALUES ('HD 219134b', 'Tempestade de Fogo')

  --tabela vendedor--
  INTO VENDEDOR (NOME) VALUES ('Comércio Galáctico')
  INTO VENDEDOR (NOME) VALUES ('Suprimentos Estel.')
  INTO VENDEDOR (NOME) VALUES ('Artesãos Cósmicos')
  INTO VENDEDOR (NOME) VALUES ('Export. Universais')
  INTO VENDEDOR (NOME) VALUES ('Posto de Neg. Int.')

    --tabela fabricaveis--
  INTO FABRICAVEIS (NOME, TIPO, DURABILIDADE, NIVEL) VALUES ('Traje Espacial', 'Utilizável', 8, 'A')
    INTO FABRICAVEIS (NOME, TIPO, DURABILIDADE, NIVEL) VALUES ('Gerador de Oxigênio', 'Utilizável', 7, 'B')
    INTO FABRICAVEIS (NOME, TIPO, DURABILIDADE, NIVEL) VALUES ('Painel Solar', 'Utilizável', 9, 'C')
    INTO FABRICAVEIS (NOME, TIPO, DURABILIDADE, NIVEL) VALUES ('Módulo de Habitat', 'Estrutura', 10, 'S')
    INTO FABRICAVEIS (NOME, TIPO, DURABILIDADE, NIVEL) VALUES ('Sint. de Alimentos', 'Utilizável', 6, 'D')
    INTO FABRICAVEIS (NOME, TIPO, DURABILIDADE, NIVEL) VALUES ('Nave Estelar', 'Locomoção', 5, 'C')
  INTO FABRICAVEIS (NOME, TIPO, DURABILIDADE, NIVEL) VALUES ('Space Station', 'Estrutura', 10, 'S')
  INTO FABRICAVEIS (NOME, TIPO, DURABILIDADE, NIVEL) VALUES ('Lunar Base', 'Estrutura', 10, 'S')
  
  --INTO FABRICAVEIS (NOME, TIPO, DURABILIDADE, NIVEL) VALUES ('Cravinhos', 'Estrutura', 10, 'S')
  --INTO FABRICAVEIS (NOME, TIPO, DURABILIDADE, NIVEL) VALUES ('Centro Compostagem', 'Pesquisa', 11, 'S')
  
  --tabela construcoes--
  INTO CONSTRUCOES (NOME, FUNCIONALIDADE) VALUES ('Módulo de Habitat', 'Moradia')
  INTO CONSTRUCOES (NOME, FUNCIONALIDADE) VALUES ('Painel Solar', 'Pesquisa')
  INTO CONSTRUCOES (NOME, FUNCIONALIDADE) VALUES ('Space Station', 'Moradia')
  INTO CONSTRUCOES (NOME, FUNCIONALIDADE) VALUES ('Lunar Base', 'Pesquisa')
  --INTO CONSTRUCOES (NOME, FUNCIONALIDADE) VALUES ('Centro Compostagem', 'Moradia')
 -- INTO CONSTRUCOES (NOME, FUNCIONALIDADE) VALUES ('Cravinhos', 'Moradia')

  --tabela equipamentos--
  INTO EQUIPAMENTOS (NOME, POTENCIA) VALUES ('Traje Espacial', 110)
  INTO EQUIPAMENTOS (NOME, POTENCIA) VALUES('Gerador de Oxigênio', 220)
  INTO EQUIPAMENTOS (NOME, POTENCIA) VALUES ('Painel Solar', 110)

  --tabela naves--
  INTO NAVE (NOME, CAPACIDADE, VELOCIDADE) VALUES ('Nave Estelar', 10000, 5000)

   --tabela aprimora--
  INTO APRIMORA (ELEMENTO, FABRICAVEL) VALUES ('Al', 'Traje Espacial')
  INTO APRIMORA (ELEMENTO, FABRICAVEL) VALUES ('Fe', 'Gerador de Oxigênio')
  INTO APRIMORA (ELEMENTO, FABRICAVEL) VALUES ('Si', 'Painel Solar')
  INTO APRIMORA (ELEMENTO, FABRICAVEL) VALUES ('C', 'Módulo de Habitat')
  INTO APRIMORA (ELEMENTO, FABRICAVEL) VALUES ('Ni', 'Sint. de Alimentos')

  --tabela cria--
  INTO CRIA (ELEMENTO, FABRICAVEL) VALUES ('Al', 'Traje Espacial')
  INTO CRIA (ELEMENTO, FABRICAVEL) VALUES ('Fe', 'Gerador de Oxigênio')
  INTO CRIA (ELEMENTO, FABRICAVEL) VALUES ('Si', 'Painel Solar')
  INTO CRIA (ELEMENTO, FABRICAVEL) VALUES ('C', 'Módulo de Habitat')
  INTO CRIA (ELEMENTO, FABRICAVEL) VALUES ('Ni', 'Sint. de Alimentos')

      --tabela especies--
  INTO ESPECIES (NOMEPLANETA, NOME, TIPO, NATUREZA, ELEMENTO, QUANTIDADE) VALUES ('Terra', 'Leão', 'Mamífero', 'Não-consciente', 'C', 12)
  INTO ESPECIES (NOMEPLANETA, NOME, TIPO, NATUREZA, ELEMENTO, QUANTIDADE) VALUES ('Terra', 'Papagaio', 'Ave', 'Não-consciente', 'O', 8)
  INTO ESPECIES (NOMEPLANETA, NOME, TIPO, NATUREZA, ELEMENTO, QUANTIDADE) VALUES ('Terra', 'Macaco', 'Mamífero', 'Consciente', 'N', 4)
  INTO ESPECIES (NOMEPLANETA, NOME, TIPO, NATUREZA, ELEMENTO, QUANTIDADE) VALUES ('Marte', 'Macaco', 'Mamífero', 'Consciente', 'N', 4)
  INTO ESPECIES (NOMEPLANETA, NOME, TIPO, NATUREZA, ELEMENTO, QUANTIDADE) VALUES ('Marte', 'Formiga Gigante', 'Inseto', 'Não-consciente', 'N', 150)
  INTO ESPECIES (NOMEPLANETA, NOME, TIPO, NATUREZA, ELEMENTO, QUANTIDADE) VALUES ('Marte', 'Serpente Marciana', 'Réptil', 'Não-consciente', 'O', 10)
  INTO ESPECIES (NOMEPLANETA, NOME, TIPO, NATUREZA, ELEMENTO, QUANTIDADE) VALUES ('Saturno', 'Criatura Anelar', 'Humanoide', 'Consciente', 'C', 3)
  INTO ESPECIES (NOMEPLANETA, NOME, TIPO, NATUREZA, ELEMENTO, QUANTIDADE) VALUES ('Saturno', 'Espectro', 'Fantasma', 'Consciente', 'O', 1)
  INTO ESPECIES (NOMEPLANETA, NOME, TIPO, NATUREZA, ELEMENTO, QUANTIDADE) VALUES ('Epsilon Prime', 'Criatura Psíquica', 'Humanoide', 'Consciente', 'O', 2)
  INTO ESPECIES (NOMEPLANETA, NOME, TIPO, NATUREZA, ELEMENTO, QUANTIDADE) VALUES ('Epsilon Prime', 'Sombra Galáctica', 'Fantasma', 'Não-consciente', 'C', 1)
  INTO ESPECIES (NOMEPLANETA, NOME, TIPO, NATUREZA, ELEMENTO, QUANTIDADE) VALUES ('Próxima b', 'Flor Astral', 'Inseto', 'Anfíbio', 'O', 30)
  INTO ESPECIES (NOMEPLANETA, NOME, TIPO, NATUREZA, ELEMENTO, QUANTIDADE) VALUES ('Próxima b', 'Viajante Dim.', 'Peixe', 'Consciente', 'Ni', 1)
  INTO ESPECIES (NOMEPLANETA, NOME, TIPO, NATUREZA, ELEMENTO, QUANTIDADE) VALUES ('Kepler-186f', 'Flutuador Nebular', 'Fantasma', 'Consciente', 'H', 3)
  INTO ESPECIES (NOMEPLANETA, NOME, TIPO, NATUREZA, ELEMENTO, QUANTIDADE) VALUES ('TRAPPIST-1d', 'Estranho Lumi', 'Réptil', 'Consciente', 'Au', 4)


    --tabela descobre_especie
  INTO DESCOBRE_ESPECIE (ASTRONAUTA, PLANETA, ESPECIE, "DATA") VALUES ('Neil Armstrong', 'Terra', 'Leão', TO_TIMESTAMP('2022-01-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO DESCOBRE_ESPECIE (ASTRONAUTA, PLANETA, ESPECIE, "DATA") VALUES('Buzz Aldrin', 'Terra', 'Papagaio', TO_TIMESTAMP('2022-01-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO DESCOBRE_ESPECIE (ASTRONAUTA, PLANETA, ESPECIE, "DATA") VALUES('Valentina Tereshkova', 'Terra', 'Macaco', TO_TIMESTAMP('2022-01-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO DESCOBRE_ESPECIE (ASTRONAUTA, PLANETA, ESPECIE, "DATA") VALUES('Neil Armstrong', 'Marte', 'Macaco', TO_TIMESTAMP('2022-01-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO DESCOBRE_ESPECIE (ASTRONAUTA, PLANETA, ESPECIE, "DATA") VALUES('Buzz Aldrin', 'Marte', 'Formiga Gigante', TO_TIMESTAMP('2022-01-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO DESCOBRE_ESPECIE (ASTRONAUTA, PLANETA, ESPECIE, "DATA") VALUES('Valentina Tereshkova', 'Marte', 'Serpente Marciana', TO_TIMESTAMP('2022-01-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO DESCOBRE_ESPECIE (ASTRONAUTA, PLANETA, ESPECIE, "DATA") VALUES('Neil Armstrong', 'Saturno', 'Criatura Anelar', TO_TIMESTAMP('2022-01-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO DESCOBRE_ESPECIE (ASTRONAUTA, PLANETA, ESPECIE, "DATA") VALUES('Buzz Aldrin', 'Saturno', 'Espectro', TO_TIMESTAMP('2022-01-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO DESCOBRE_ESPECIE (ASTRONAUTA, PLANETA, ESPECIE, "DATA") VALUES('Neil Armstrong', 'Epsilon Prime', 'Criatura Psíquica', TO_TIMESTAMP('2022-01-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO DESCOBRE_ESPECIE (ASTRONAUTA, PLANETA, ESPECIE, "DATA") VALUES('Buzz Aldrin', 'Epsilon Prime', 'Sombra Galáctica', TO_TIMESTAMP('2022-01-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO DESCOBRE_ESPECIE (ASTRONAUTA, PLANETA, ESPECIE, "DATA") VALUES('Neil Armstrong', 'Próxima b', 'Flor Astral', TO_TIMESTAMP('2022-01-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO DESCOBRE_ESPECIE (ASTRONAUTA, PLANETA, ESPECIE, "DATA") VALUES('Buzz Aldrin', 'Próxima b', 'Viajante Dim.', TO_TIMESTAMP('2022-01-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO DESCOBRE_ESPECIE (ASTRONAUTA, PLANETA, ESPECIE, "DATA") VALUES('Neil Armstrong', 'Kepler-186f', 'Flutuador Nebular', TO_TIMESTAMP('2022-01-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO DESCOBRE_ESPECIE (ASTRONAUTA, PLANETA, ESPECIE, "DATA") VALUES('Neil Armstrong', 'TRAPPIST-1d', 'Estranho Lumi', TO_TIMESTAMP('2022-01-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'))


  --tabela mercado--
  INTO MERCADO (ASTRONAUTA, VENDEDOR, "DATA") VALUES ('Neil Armstrong', 'Comércio Galáctico', TO_TIMESTAMP('2022-01-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO MERCADO (ASTRONAUTA, VENDEDOR, "DATA") VALUES('Yuri Gagarin', 'Suprimentos Estel.', TO_TIMESTAMP('2022-02-15 09:30:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO MERCADO (ASTRONAUTA, VENDEDOR, "DATA") VALUES('Valentina Tereshkova', 'Artesãos Cósmicos', TO_TIMESTAMP('2022-03-20 15:45:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO MERCADO (ASTRONAUTA, VENDEDOR, "DATA") VALUES ('Buzz Aldrin', 'Export. Universais', TO_TIMESTAMP('2022-04-10 08:20:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO MERCADO (ASTRONAUTA, VENDEDOR, "DATA") VALUES('Sally Ride', 'Posto de Neg. Int.', TO_TIMESTAMP('2022-05-05 18:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO MERCADO (ASTRONAUTA, VENDEDOR, "DATA") VALUES('Yuri Gagarin', 'Comércio Galáctico', TO_TIMESTAMP('2022-06-12 14:30:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO MERCADO (ASTRONAUTA, VENDEDOR, "DATA") VALUES('Valentina Tereshkova', 'Suprimentos Estel.', TO_TIMESTAMP('2022-07-18 10:15:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO MERCADO (ASTRONAUTA, VENDEDOR, "DATA") VALUES('Buzz Aldrin', 'Artesãos Cósmicos', TO_TIMESTAMP('2022-08-22 20:45:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO MERCADO (ASTRONAUTA, VENDEDOR, "DATA") VALUES('Sally Ride', 'Export. Universais', TO_TIMESTAMP('2022-09-30 16:10:00', 'YYYY-MM-DD HH24:MI:SS'))
  INTO MERCADO (ASTRONAUTA, VENDEDOR, "DATA") VALUES('Neil Armstrong', 'Posto de Neg. Int.', TO_TIMESTAMP('2022-10-25 08:55:00', 'YYYY-MM-DD HH24:MI:SS'))

  --tabela venda_fabricavel--
  INTO VENDE_FABRICAVEL (ASTRONAUTA, "DATA", VENDEDOR, FABRICAVEL, QUANTIDADE) VALUES ('Buzz Aldrin', TO_TIMESTAMP('2022-04-10 08:20:00', 'YYYY-MM-DD HH24:MI:SS'), 'Export. Universais', 'Módulo de Habitat', 10)
  INTO VENDE_FABRICAVEL (ASTRONAUTA, "DATA", VENDEDOR, FABRICAVEL, QUANTIDADE) VALUES('Sally Ride', TO_TIMESTAMP('2022-05-05 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Posto de Neg. Int.', 'Sint. de Alimentos', 30)
  INTO VENDE_FABRICAVEL (ASTRONAUTA, "DATA", VENDEDOR, FABRICAVEL, QUANTIDADE) VALUES('Yuri Gagarin', TO_TIMESTAMP('2022-06-12 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Comércio Galáctico', 'Traje Espacial', 15)
  INTO VENDE_FABRICAVEL (ASTRONAUTA, "DATA", VENDEDOR, FABRICAVEL, QUANTIDADE) VALUES('Valentina Tereshkova', TO_TIMESTAMP('2022-07-18 10:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'Suprimentos Estel.', 'Gerador de Oxigênio', 12)
  INTO VENDE_FABRICAVEL (ASTRONAUTA, "DATA", VENDEDOR, FABRICAVEL, QUANTIDADE) VALUES('Buzz Aldrin', TO_TIMESTAMP('2022-08-22 20:45:00', 'YYYY-MM-DD HH24:MI:SS'), 'Artesãos Cósmicos', 'Painel Solar', 18)
  INTO VENDE_FABRICAVEL (ASTRONAUTA, "DATA", VENDEDOR, FABRICAVEL, QUANTIDADE) VALUES('Sally Ride', TO_TIMESTAMP('2022-09-30 16:10:00', 'YYYY-MM-DD HH24:MI:SS'), 'Export. Universais', 'Módulo de Habitat', 8)
  INTO VENDE_FABRICAVEL (ASTRONAUTA, "DATA", VENDEDOR, FABRICAVEL, QUANTIDADE) VALUES('Neil Armstrong', TO_TIMESTAMP('2022-10-25 08:55:00', 'YYYY-MM-DD HH24:MI:SS'), 'Posto de Neg. Int.', 'Sint. de Alimentos', 25)

  --tabela venda_elemento--
  INTO VENDE_ELEMENTO (ASTRONAUTA, "DATA", VENDEDOR, ELEMENTO, QUANTIDADE) VALUES ('Neil Armstrong', TO_TIMESTAMP('2022-01-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Comércio Galáctico', 'O', 100)
  INTO VENDE_ELEMENTO (ASTRONAUTA, "DATA", VENDEDOR, ELEMENTO, QUANTIDADE) VALUES('Yuri Gagarin', TO_TIMESTAMP('2022-02-15 09:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Suprimentos Estel.', 'H', 50)
  INTO VENDE_ELEMENTO (ASTRONAUTA, "DATA", VENDEDOR, ELEMENTO, QUANTIDADE) VALUES('Valentina Tereshkova', TO_TIMESTAMP('2022-03-20 15:45:00', 'YYYY-MM-DD HH24:MI:SS'), 'Artesãos Cósmicos', 'C', 75)
  INTO VENDE_ELEMENTO (ASTRONAUTA, "DATA", VENDEDOR, ELEMENTO, QUANTIDADE) VALUES('Buzz Aldrin', TO_TIMESTAMP('2022-04-10 08:20:00', 'YYYY-MM-DD HH24:MI:SS'), 'Export. Universais', 'N', 30)
  INTO VENDE_ELEMENTO (ASTRONAUTA, "DATA", VENDEDOR, ELEMENTO, QUANTIDADE) VALUES('Sally Ride', TO_TIMESTAMP('2022-05-05 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Posto de Neg. Int.', 'Fe', 20)
  INTO VENDE_ELEMENTO (ASTRONAUTA, "DATA", VENDEDOR, ELEMENTO, QUANTIDADE) VALUES('Yuri Gagarin', TO_TIMESTAMP('2022-06-12 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Comércio Galáctico', 'O', 75)
  INTO VENDE_ELEMENTO (ASTRONAUTA, "DATA", VENDEDOR, ELEMENTO, QUANTIDADE) VALUES('Valentina Tereshkova', TO_TIMESTAMP('2022-07-18 10:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'Suprimentos Estel.', 'H', 40)
  INTO VENDE_ELEMENTO (ASTRONAUTA, "DATA", VENDEDOR, ELEMENTO, QUANTIDADE) VALUES('Buzz Aldrin', TO_TIMESTAMP('2022-08-22 20:45:00', 'YYYY-MM-DD HH24:MI:SS'), 'Artesãos Cósmicos', 'C', 60)
  INTO VENDE_ELEMENTO (ASTRONAUTA, "DATA", VENDEDOR, ELEMENTO, QUANTIDADE) VALUES('Sally Ride', TO_TIMESTAMP('2022-09-30 16:10:00', 'YYYY-MM-DD HH24:MI:SS'), 'Export. Universais', 'N', 20)
  INTO VENDE_ELEMENTO (ASTRONAUTA, "DATA", VENDEDOR, ELEMENTO, QUANTIDADE) VALUES('Neil Armstrong', TO_TIMESTAMP('2022-10-25 08:55:00', 'YYYY-MM-DD HH24:MI:SS'), 'Posto de Neg. Int.', 'Fe', 15)


    --tabela local
  
  INTO "LOCAL" (POSICAOX, POSICAOY, NOME_ASTRONAUTA, FABRICAVEL) VALUES (522, 812, 'Neil Armstrong', 'Space Station')
  INTO "LOCAL" (POSICAOX, POSICAOY, NOME_ASTRONAUTA, FABRICAVEL) VALUES (278, 231, 'Yuri Gagarin', 'Painel Solar')
  
  --INTO "LOCAL" (POSICAOX, POSICAOY, NOME_ASTRONAUTA, FABRICAVEL) VALUES (2222278, 14140000, 'Buzz Aldrin', 'Cravinhos')
  --INTO "LOCAL" (POSICAOX, POSICAOY, NOME_ASTRONAUTA, FABRICAVEL) VALUES (6969, 666, 'Sally Ride', 'Centro Compostagem')

  INTO "LOCAL" (POSICAOX, POSICAOY, NOME_ASTRONAUTA, FABRICAVEL) VALUES (52, 821, 'Neil Armstrong', 'Módulo de Habitat')
  INTO "LOCAL" (POSICAOX, POSICAOY, NOME_ASTRONAUTA, FABRICAVEL) VALUES (5, 8, 'Neil Armstrong', 'Lunar Base')

  --tabela rota
  INTO ROTA (ORIGEM, DESTINO, DISTANCIA_TOTAL) VALUES ('Terra', 'Marte', 225)
  INTO ROTA (ORIGEM, DESTINO, DISTANCIA_TOTAL) VALUES ('Marte', 'Terra', 225)
  INTO ROTA (ORIGEM, DESTINO, DISTANCIA_TOTAL) VALUES ('Júpiter', 'Epsilon Prime', 855)
  INTO ROTA (ORIGEM, DESTINO, DISTANCIA_TOTAL) VALUES ('Epsilon Prime', 'Júpiter', 855)
  INTO ROTA (ORIGEM, DESTINO, DISTANCIA_TOTAL) VALUES ('Júpiter', 'Saturno', 678)
  INTO ROTA (ORIGEM, DESTINO, DISTANCIA_TOTAL) VALUES ('Kepler-186f', 'Júpiter', 2200)
  INTO ROTA (ORIGEM, DESTINO, DISTANCIA_TOTAL) VALUES ('Júpiter', 'Kepler-186f', 2200)
  INTO ROTA (ORIGEM, DESTINO, DISTANCIA_TOTAL) VALUES ('Marte', 'Júpiter', 412)
  INTO ROTA (ORIGEM, DESTINO, DISTANCIA_TOTAL) VALUES ('Saturno', 'Epsilon Prime', 987)
  INTO ROTA (ORIGEM, DESTINO, DISTANCIA_TOTAL) VALUES ('Epsilon Prime', 'Próxima b', 150)
  INTO ROTA (ORIGEM, DESTINO, DISTANCIA_TOTAL) VALUES ('Próxima b', 'Kepler-186f', 80)
  INTO ROTA (ORIGEM, DESTINO, DISTANCIA_TOTAL) VALUES ('Kepler-186f', 'TRAPPIST-1d', 200)
  INTO ROTA (ORIGEM, DESTINO, DISTANCIA_TOTAL) VALUES ('TRAPPIST-1d', 'Gliese 581g', 90)
  INTO ROTA (ORIGEM, DESTINO, DISTANCIA_TOTAL) VALUES ('Gliese 581g', 'HD 219134b', 160)
  INTO ROTA (ORIGEM, DESTINO, DISTANCIA_TOTAL) VALUES ('HD 219134b', 'Gliese 581g', 160)
  INTO ROTA (ORIGEM, DESTINO, DISTANCIA_TOTAL) VALUES ('Gliese 581g', 'TRAPPIST-1d', 1620)



    --tabela viagem
    INTO VIAGEM (ORIGEM, DESTINO, "DATA", ASTRONAUTA) VALUES  ('Terra', 'Marte', TO_TIMESTAMP('2023-04-01 11:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'Neil Armstrong')
    INTO VIAGEM (ORIGEM, DESTINO, "DATA", ASTRONAUTA) VALUES ('Marte', 'Terra', TO_TIMESTAMP('2023-07-01 00:45:00', 'YYYY-MM-DD HH24:MI:SS'), 'Neil Armstrong')
    INTO VIAGEM (ORIGEM, DESTINO, "DATA", ASTRONAUTA) VALUES ('Júpiter', 'Epsilon Prime', TO_TIMESTAMP('2023-05-15 15:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Yuri Gagarin')
    INTO VIAGEM (ORIGEM, DESTINO, "DATA", ASTRONAUTA) VALUES ('Kepler-186f', 'Júpiter', TO_TIMESTAMP('2023-05-15 15:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Yuri Gagarin')
    INTO VIAGEM (ORIGEM, DESTINO, "DATA", ASTRONAUTA) VALUES ('Júpiter', 'Saturno', TO_TIMESTAMP('2023-06-20 19:45:00', 'YYYY-MM-DD HH24:MI:SS'), 'Valentina Tereshkova')
    INTO VIAGEM (ORIGEM, DESTINO, "DATA", ASTRONAUTA) VALUES ('Saturno', 'Epsilon Prime', TO_TIMESTAMP('2023-07-10 00:20:00', 'YYYY-MM-DD HH24:MI:SS'), 'Buzz Aldrin')
    INTO VIAGEM (ORIGEM, DESTINO, "DATA", ASTRONAUTA) VALUES ('Saturno', 'Epsilon Prime', TO_TIMESTAMP('2023-07-15 07:40:00', 'YYYY-MM-DD HH24:MI:SS'), 'Buzz Aldrin')
    INTO VIAGEM (ORIGEM, DESTINO, "DATA", ASTRONAUTA) VALUES ('Epsilon Prime', 'Próxima b', TO_TIMESTAMP('2023-11-01 12:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Neil Armstrong')
    INTO VIAGEM (ORIGEM, DESTINO, "DATA", ASTRONAUTA) VALUES ('Próxima b', 'Kepler-186f', TO_TIMESTAMP('2023-10-15 16:50:00', 'YYYY-MM-DD HH24:MI:SS'), 'Yuri Gagarin')
    INTO VIAGEM (ORIGEM, DESTINO, "DATA", ASTRONAUTA) VALUES ('Kepler-186f', 'TRAPPIST-1d', TO_TIMESTAMP('2023-11-30 07:55:00', 'YYYY-MM-DD HH24:MI:SS'), 'Valentina Tereshkova')
    INTO VIAGEM (ORIGEM, DESTINO, "DATA", ASTRONAUTA) VALUES ('Epsilon Prime', 'Próxima b', TO_TIMESTAMP('2023-09-01 12:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Neil Armstrong')
    INTO VIAGEM (ORIGEM, DESTINO, "DATA", ASTRONAUTA) VALUES ('Próxima b', 'Kepler-186f', TO_TIMESTAMP('2023-10-15 16:50:00', 'YYYY-MM-DD HH24:MI:SS'), 'Neil Armstrong')
    INTO VIAGEM (ORIGEM, DESTINO, "DATA", ASTRONAUTA) VALUES ('Kepler-186f', 'TRAPPIST-1d', TO_TIMESTAMP('2023-11-20 21:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'Valentina Tereshkova')
    INTO VIAGEM (ORIGEM, DESTINO, "DATA", ASTRONAUTA) VALUES ('TRAPPIST-1d', 'Gliese 581g', TO_TIMESTAMP('2023-12-10 01:40:00', 'YYYY-MM-DD HH24:MI:SS'), 'Buzz Aldrin')
    INTO VIAGEM (ORIGEM, DESTINO, "DATA", ASTRONAUTA) VALUES ('Gliese 581g', 'HD 219134b', TO_TIMESTAMP('2024-01-05 11:20:00', 'YYYY-MM-DD HH24:MI:SS'), 'Sally Ride')
    INTO VIAGEM (ORIGEM, DESTINO, "DATA", ASTRONAUTA) VALUES ('Gliese 581g', 'TRAPPIST-1d', TO_TIMESTAMP('2023-12-10 17:40:00', 'YYYY-MM-DD HH24:MI:SS'), 'Buzz Aldrin')
    INTO VIAGEM (ORIGEM, DESTINO, "DATA", ASTRONAUTA) VALUES ('HD 219134b', 'Gliese 581g', TO_TIMESTAMP('2024-07-05 00:50:00', 'YYYY-MM-DD HH24:MI:SS'), 'Sally Ride')


SELECT * FROM dual;
