CREATE TABLE ASTRONAUTA(
    NOME VARCHAR2(20) NOT NULL PRIMARY KEY,
    NASCIMENTO TIMESTAMP NOT NULL
);

CREATE TABLE ESTRELA(
    NOME VARCHAR2(20) PRIMARY KEY,
    TAMANHO CHAR(8) CHECK (TAMANHO IN ('Pequeno', 'Médio', 'Grande')),
    BINARIO NUMBER(1)
);

CREATE TABLE PLANETA(
    NOME VARCHAR2(20) NOT NULL,
    TAMANHO CHAR(8) CHECK (TAMANHO IN ('Pequeno', 'Médio', 'Grande')),
    NIVEL_DE_SEGURANCA CHAR(8) CHECK (NIVEL_DE_SEGURANCA IN ('Baixo', 'Médio', 'Alto')),
    DISTANCIA_DA_ESTRELA NUMBER,
    CALOR NUMBER,
    TRANSLACAO NUMBER,
    ROTACAO NUMBER,
    ESTRELA VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_PLANETA PRIMARY KEY(NOME),
    CONSTRAINT FK1_PLANETA FOREIGN KEY(ESTRELA)
                REFERENCES ESTRELA(NOME)
                ON DELETE CASCADE
);

CREATE TABLE DESCOBRE_PLANETA(
    "DATA" TIMESTAMP NOT NULL,
    ASTRONAUTA VARCHAR2(20) NOT NULL,
    PLANETA VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_DESCOBRE_PLANETA PRIMARY KEY(ASTRONAUTA, PLANETA),
    CONSTRAINT FK1_DESCOBRE_PLANETA FOREIGN KEY(ASTRONAUTA)
                REFERENCES ASTRONAUTA(NOME)
                ON DELETE CASCADE,
    CONSTRAINT FK2_DESCOBRE_PLANETA FOREIGN KEY(PLANETA)
                REFERENCES PLANETA(NOME)
                ON DELETE CASCADE
);

CREATE TABLE LUAS(
    NOME VARCHAR2(20) NOT NULL,
    PLANETA VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_LUAS PRIMARY KEY(PLANETA, NOME),
    CONSTRAINT FK_LUAS FOREIGN KEY(PLANETA)
                REFERENCES PLANETA(NOME)
                ON DELETE CASCADE
);

CREATE TABLE BIOMA( --MUDAR
    TIPO CHAR(20) NOT NULL PRIMARY KEY, 
    NIVEL_DE_RADIACAO CHAR(8) CHECK (NIVEL_DE_RADIACAO IN ('Baixo', 'Médio', 'Alto')) ,
    NIVEL_DE_TOXIDADE CHAR(8) CHECK (NIVEL_DE_TOXIDADE IN ('Baixo', 'Médio', 'Alto'))
);

CREATE TABLE AMBIENTE(
    PLANETA VARCHAR2(20) NOT NULL,
    BIOMA CHAR(20) NOT NULL,
    CONSTRAINT PK_AMBIENTE PRIMARY KEY(PLANETA),
    CONSTRAINT FK_AMBIENTE FOREIGN KEY(BIOMA)
                REFERENCES BIOMA(TIPO)
                ON DELETE SET NULL
);

CREATE TABLE ELEMENTO_QUIMICO(
    SIGLA CHAR(3) NOT NULL PRIMARY KEY
);

CREATE TABLE MINERIO(
    NOME CHAR(20) NOT NULL PRIMARY KEY,
    TIPO CHAR(20) NOT NULL CHECK (TIPO  IN ('Metálico', 'Precioso', 'Não Metálico')),
    DUREZA CHAR(3),
    ELEMENTO CHAR(3),
    QUANTIDADE NUMBER,
    CONSTRAINT CK_DUREZA CHECK (DUREZA BETWEEN 1 AND 10),
    CONSTRAINT FK_MINERIO FOREIGN KEY(ELEMENTO)
                REFERENCES ELEMENTO_QUIMICO(SIGLA)
                ON DELETE SET NULL              
);

CREATE TABLE POSSUI(
    AMBIENTE VARCHAR2(20) NOT NULL,
    MINERIO CHAR(20) NOT NULL,
    CONSTRAINT PK_POSSUI PRIMARY KEY(AMBIENTE, MINERIO),
    CONSTRAINT FK1_POSSUI FOREIGN KEY (AMBIENTE)
                REFERENCES AMBIENTE(PLANETA)
                ON DELETE SET NULL,
    CONSTRAINT FK2_POSSUI FOREIGN KEY (MINERIO)
                REFERENCES MINERIO(NOME)
                ON DELETE SET NULL
);

CREATE TABLE TIPO_DE_FAUNA_FLORA(
    AMBIENTE VARCHAR2(20) NOT NULL,
    TIPO CHAR(20) NOT NULL,
    CONSTRAINT PK_FAUNA_FLORA PRIMARY KEY(AMBIENTE, TIPO),
    CONSTRAINT FK_FAUNA_FLORA FOREIGN KEY(AMBIENTE)
                REFERENCES AMBIENTE(PLANETA)
                ON DELETE SET NULL
);

CREATE TABLE TIPO_DE_MINERIO(
    AMBIENTE VARCHAR2(20) NOT NULL,
    TIPO CHAR(20) NOT NULL,
    CONSTRAINT PK_TIPO_DE_MINERIO PRIMARY KEY(AMBIENTE, TIPO),
    CONSTRAINT FK_TIPO_DE__MINERIO FOREIGN KEY(AMBIENTE)
                REFERENCES AMBIENTE(PLANETA)
                ON DELETE SET NULL
);

CREATE TABLE PERIGO(
    AMBIENTE VARCHAR2(20) NOT NULL,
    NOME CHAR(20) NOT NULL,
    CONSTRAINT PK_PERIGO PRIMARY KEY(AMBIENTE, NOME),
    CONSTRAINT FK_PERIGO FOREIGN KEY(AMBIENTE)
                REFERENCES AMBIENTE(PLANETA)
                ON DELETE SET NULL
);

CREATE TABLE VENDEDOR(
    NOME CHAR(20) NOT NULL PRIMARY KEY
);

CREATE TABLE FABRICAVEIS(
    NOME VARCHAR2(20) NOT NULL PRIMARY KEY,
    TIPO CHAR(20) CHECK (TIPO  IN ('Utilizável', 'Estrutura', 'Locomoção')),
    DURABILIDADE NUMBER NOT NULL,
    NIVEL CHAR(1),
    CONSTRAINT CK_DURABILIDADE CHECK (DURABILIDADE BETWEEN 1 AND 10),
    CONSTRAINT CK_NIVEL CHECK (NIVEL IN ('S', 'A', 'B', 'C', 'D', 'E', 'F'))
);

CREATE TABLE CONSTRUCOES(
    NOME VARCHAR2(20) NOT NULL PRIMARY KEY,
    FUNCIONALIDADE CHAR(20) NOT NULL CHECK (FUNCIONALIDADE IN ('Moradia', 'Militar', 'Pesquisa')),
    CONSTRAINT FK_CONSTRUCOES FOREIGN KEY(NOME)
                REFERENCES FABRICAVEIS(NOME)
                ON DELETE SET NULL
);

CREATE TABLE EQUIPAMENTOS (
    NOME VARCHAR2(20) NOT NULL PRIMARY KEY,
    POTENCIA NUMBER NOT NULL,
    CONSTRAINT CK_POTENCIA CHECK (POTENCIA = 110 OR POTENCIA = 220),
    CONSTRAINT FK_EQUIPAMENTOS FOREIGN KEY (NOME)
        REFERENCES FABRICAVEIS (NOME)
        ON DELETE SET NULL
);


CREATE TABLE NAVE(
    NOME VARCHAR2(20) NOT NULL PRIMARY KEY,
    CAPACIDADE NUMBER NOT NULL,
    VELOCIDADE NUMBER NOT NULL,
    CONSTRAINT FK_NAVE FOREIGN KEY(NOME)
                REFERENCES FABRICAVEIS(NOME)
                ON DELETE SET NULL
);

CREATE TABLE APRIMORA(
    ELEMENTO CHAR(3) NOT NULL,
    FABRICAVEL VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_APRIMORA PRIMARY KEY(ELEMENTO, FABRICAVEL),
    CONSTRAINT FK1_APRIMORA FOREIGN KEY(ELEMENTO)
                REFERENCES ELEMENTO_QUIMICO(SIGLA)
                ON DELETE SET NULL,
    CONSTRAINT FK2_APRIMORA FOREIGN KEY(FABRICAVEL)
                REFERENCES FABRICAVEIS(NOME)
                ON DELETE SET NULL            
);

CREATE TABLE CRIA(
    ELEMENTO CHAR(3) NOT NULL,
    FABRICAVEL VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_CRIA PRIMARY KEY(ELEMENTO, FABRICAVEL),
    CONSTRAINT FK1_CRIA FOREIGN KEY(ELEMENTO)
                REFERENCES ELEMENTO_QUIMICO(SIGLA)
                ON DELETE SET NULL,
    CONSTRAINT FK2_CRIA FOREIGN KEY(FABRICAVEL)
                REFERENCES FABRICAVEIS(NOME)
                ON DELETE SET NULL     
);
CREATE TABLE ESPECIES(
    NOMEPLANETA VARCHAR2(20) NOT NULL,
    NOME VARCHAR2(20) NOT NULL,
    TIPO CHAR(10) NOT NULL,
    NATUREZA CHAR(20), 
    ELEMENTO CHAR(3),
    QUANTIDADE NUMBER NOT NULL,
    CONSTRAINT CK_ESPECIES CHECK (TIPO  IN ('Mamífero', 'Ave', 'Réptil', 'Anfíbio', 'Peixe', 'Fantasma', 'Inseto', 'Humanoide')),
    CONSTRAINT PK_ESPECIE PRIMARY KEY(NOMEPLANETA, NOME),
    CONSTRAINT FK1_ESPECIE FOREIGN KEY(NOMEPLANETA)
                    REFERENCES AMBIENTE(PLANETA)
                    ON DELETE SET NULL,
    CONSTRAINT FK2_ESPECIE FOREIGN KEY(ELEMENTO)
                    REFERENCES ELEMENTO_QUIMICO(SIGLA)
                    ON DELETE SET NULL
);

CREATE TABLE DESCOBRE_ESPECIE(
    ASTRONAUTA VARCHAR2(20) NOT NULL,
    PLANETA VARCHAR2(20) NOT NULL,
    ESPECIE VARCHAR2(20) NOT NULL,
    "DATA" TIMESTAMP NOT NULL,
    CONSTRAINT PK_DESCOBRE_ESPECIE PRIMARY KEY(ASTRONAUTA, PLANETA, ESPECIE),
    CONSTRAINT FK1_DESCOBRE_ESPECIE FOREIGN KEY(ASTRONAUTA)
                    REFERENCES ASTRONAUTA(NOME)
                    ON DELETE SET NULL,
    CONSTRAINT FK2_DESCOBRE_ESPECIE FOREIGN KEY(PLANETA, ESPECIE)
                    REFERENCES ESPECIES(NOMEPLANETA, NOME)
                    ON DELETE SET NULL
);


CREATE TABLE MERCADO(
    ASTRONAUTA VARCHAR2(20) NOT NULL,
    VENDEDOR CHAR(20) NOT NULL,
    "DATA" TIMESTAMP NOT NULL,
    CONSTRAINT PK_MERCADO PRIMARY KEY(ASTRONAUTA, VENDEDOR, "DATA"),
    CONSTRAINT FK1_MERCADO FOREIGN KEY(ASTRONAUTA)
                REFERENCES ASTRONAUTA(NOME)
                ON DELETE SET NULL,
    CONSTRAINT FK2_MERCADO FOREIGN KEY(VENDEDOR)
                REFERENCES VENDEDOR(NOME)
                ON DELETE SET NULL
);

CREATE TABLE VENDE_FABRICAVEL(
    ASTRONAUTA VARCHAR2(20) NOT NULL,
    "DATA" TIMESTAMP NOT NULL,
    VENDEDOR CHAR(20) NOT NULL,
    FABRICAVEL VARCHAR2(20) NOT NULL,
    QUANTIDADE NUMBER NOT NULL,
    CONSTRAINT PK_VENDE_FABRICAVEL PRIMARY KEY(ASTRONAUTA, "DATA", VENDEDOR, FABRICAVEL),
    CONSTRAINT FK1_VENDE_FABRICAVEL FOREIGN KEY(ASTRONAUTA, "DATA", VENDEDOR)
                REFERENCES MERCADO(ASTRONAUTA, "DATA", VENDEDOR)
                ON DELETE SET NULL,
    CONSTRAINT FK2_VENDE_FABRICAVEL FOREIGN KEY(FABRICAVEL)
                REFERENCES FABRICAVEIS(NOME)
);

CREATE TABLE VENDE_ELEMENTO(
    ASTRONAUTA VARCHAR2(20) NOT NULL,
    "DATA" TIMESTAMP NOT NULL,
    VENDEDOR CHAR(20) NOT NULL,
    ELEMENTO CHAR(3) NOT NULL,
    QUANTIDADE NUMBER NOT NULL,
    CONSTRAINT PK_VENDE_ELEMENTO PRIMARY KEY(ASTRONAUTA, "DATA", VENDEDOR, ELEMENTO),
    CONSTRAINT FK1_VENDE_ELEMENTO FOREIGN KEY(ASTRONAUTA, "DATA", VENDEDOR)
                REFERENCES MERCADO(ASTRONAUTA, "DATA", VENDEDOR)
                ON DELETE SET NULL,
    CONSTRAINT FK2_VENDE_ELEMENTO FOREIGN KEY(ELEMENTO)
                REFERENCES ELEMENTO_QUIMICO(SIGLA)
                ON DELETE SET NULL
);

CREATE TABLE "LOCAL"(
    POSICAOX NUMBER NOT NULL,
    POSICAOY NUMBER NOT NULL,
    NOME_ASTRONAUTA VARCHAR2(20) NOT NULL, 
    FABRICAVEL  VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_LOCAL PRIMARY KEY(POSICAOX, POSICAOY),
    CONSTRAINT FK1_LOCAL FOREIGN KEY(NOME_ASTRONAUTA) 
                REFERENCES ASTRONAUTA(NOME)
                ON DELETE SET NULL,
    CONSTRAINT FK2_LOCAL FOREIGN KEY(FABRICAVEL) 
                REFERENCES CONSTRUCOES(NOME)
                ON DELETE SET NULL
);

CREATE TABLE ROTA(
    ORIGEM VARCHAR(20) NOT NULL,
    DESTINO VARCHAR(20) NOT NULL,
    DISTANCIA_TOTAL NUMBER NOT NULL,
    CONSTRAINT PK_ROTA PRIMARY KEY(ORIGEM, DESTINO),
    CONSTRAINT FK1_ROTA FOREIGN KEY(ORIGEM)
                 REFERENCES PLANETA(NOME)
                 ON DELETE CASCADE,
    CONSTRAINT FK2_ROTA FOREIGN KEY(DESTINO)
                 REFERENCES PLANETA(NOME)
                 ON DELETE CASCADE
);

CREATE TABLE VIAGEM(
    ORIGEM VARCHAR2(20) NOT NULL,
    DESTINO VARCHAR2(20) NOT NULL,
    "DATA" TIMESTAMP NOT NULL,
    ASTRONAUTA VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_VIAGEM PRIMARY KEY(ORIGEM, DESTINO, "DATA", ASTRONAUTA),
    CONSTRAINT FK1_VIAGEM FOREIGN KEY(ORIGEM, DESTINO)  
                REFERENCES ROTA(ORIGEM, DESTINO)  
                ON DELETE CASCADE,
    CONSTRAINT FK2_VIAGEM FOREIGN KEY(ASTRONAUTA)
                REFERENCES ASTRONAUTA(NOME)
                ON DELETE CASCADE
);

